#!/bin/bash

# Logging functions ─────────────────────────────────────────────────────────────────────
log() {
    echo -e "\033[1;36m💡 [INFO]\033[0m $1"
}
success() {
    echo -e "\033[1;32m✅ [SUCCESS]\033[0m $1"
}
warning() {
    echo -e "\033[1;33m⚠️  [WARNING]\033[0m $1"
}
line() {
    echo "────────────────────────────────────────────────────────────────────────"
}

# Init logic ───────────────────────────────────────────────────────────────────────────
clear
set -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"

log "Uninstalling syncrab..."
cargo uninstall syncrab || warning "syncrab not found."
line

success "Uninstallation complete."